export const CREATE_COUNTER = 'CREATE_COUNTER';

export const CREATE_PROJECT = 'CREATE_PROJECT';

export const DELETE_COUNTER = 'DELETE_COUNTER';

export const DELETE_PROJECT = 'DELETE_PROJECT';

export const MANAGE_COUNTER = 'MANAGE_COUNTER';

export const MANAGE_PROJECT = 'MANAGE_PROJECT';

export const NO_OP = 'NO_OP';

export const RESTORE_FROM_LOCAL_STORAGE = 'RESTORE_FROM_LOCAL_STORAGE';

export const TOGGLE_THEME = 'TOGGLE_THEME';
